# @package _group_

defaults:
  - _self_
  - data: multitrack-stem-gmd
  - model: idm
  - callbacks: default
  - paths: default
  - hydra: default
  - tuner: none
  - logger: custom
  - local # Machine-specific config

# Global parameters
seed: 1964
sampling_rate: 44100
n_drum_kits: 6
feature_dim: 32 # Dimension of the feature extractor output
sample_duration: 1.0 # in seconds
version: "full"
train_classes:
  - CY_CR
  - CY_RD
  - HH_CHH
  - HH_OHH
  - KD
  - SD
  - TT_HFT
  - TT_HMT
  - TT_LMT

task_name: "train"
train: True
test: True

ckpt_path: null

# Trainer
trainer:
  _target_: lightning.pytorch.trainer.Trainer
  accelerator: "gpu"
  devices: 1
  max_epochs: 6000
  max_steps: 400000
  min_epochs: 50
  check_val_every_n_epoch: 1
  gradient_clip_val: 1.0
  deterministic: False
  limit_val_batches: 250
  enable_progress_bar: True

extras:
  print_config: True
